import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import type { GetServerSideProps } from "next";
import { Container } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import config from "../lib/config.js";
import { GalleryFor } from "../components/gallery";
import { SectionFolders } from "../components/nav/section-folders";
import { SectionsNav } from "../components/nav/sections-nav";
import { firstQueryValue, type UISection } from "../components/ui-types";

interface HomeProps {
	sections: UISection[];
}

export default function Home({ sections = [] }: HomeProps) {
	const router = useRouter();
	const sectionQuery = firstQueryValue(router.query.section);
	const sectionId = Number.parseInt(sectionQuery ?? "", 10);
	const activeSectionId = Number.isInteger(sectionId) ? sectionId : -1;
	const section = sections[activeSectionId];
	const folder = firstQueryValue(router.query.folder) ?? "";

	return (
		<>
			<Head>
				<title>Travel Photo Album</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="bg-dark text-light">
				<Container fluid className="d-flex">
					<div className="flex-grow-0" style={{ width: "25%" }}>
						<h4>Travel Photo Album</h4>
						<SectionsNav sections={sections} sectionId={activeSectionId} />
						<SectionFolders section={section} folder={folder} />
					</div>
					<div className="flex-grow-1" style={{ width: "75%" }}>
						{section && <GalleryFor section={section} folder={folder} />}
					</div>
				</Container>

				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{" "}
						<span className={styles.logo}>
							<Image
								src="/vercel.svg"
								alt="Vercel Logo"
								width={72}
								height={16}
							/>
						</span>
					</a>
				</footer>
			</div>
		</>
	);
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
	const sections = Array.isArray(config?.sections) ? config.sections : [];

	return {
		props: {
			sections: sections.map((section, index) => ({ ...section, id: index })),
		},
	};
};
