import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Container, Nav } from "react-bootstrap";
import Link from "next/link";
import config from "../config.json";
import { GalleryFor } from "../components/gallery.js";
import { useRouter } from "next/router.js";

export default function Home({ sections }) {
	const router = useRouter();
	const sectionId = Number(router.query.section);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="bg-dark text-light">
				<Container className="d-flex">
					<div className="flex-grow-0" style={{ width: "25%" }}>
						<h4>Travel Photo Album</h4>
						<Nav variant="pills">
							{sections.map((x, index) => (
								<Nav.Link
									key={index}
									className={index === sectionId ? "active text-light" : ""}
									as={"li"}
								>
									<Link href={`?section=${index}`}>
										<a
											className={index === sectionId ? "active text-light" : ""}
										>
											{x.name}
										</a>
									</Link>
								</Nav.Link>
							))}
						</Nav>
					</div>
					<div className="flex-grow-1" style={{ width: "75%" }}>
						{sectionId >= 0 && (
							<GalleryFor sectionId={sectionId} section={sections[sectionId]} />
						)}
					</div>
				</Container>
			</div>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</>
	);
}

export function getServerSideProps() {
	return {
		props: {
			sections: config.sections,
		},
	};
}
